name: /Users/gtaddei/Desktop/Progetti/Grano.IT/Risorse/python/grano_experiments
channels:
  - https://conda.anaconda.org/conda-forge
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch==2.3.1
  - pytorch-lightning==2.5.0
  - pytorch-forecasting
  - h5py
  - psutil
  - matplotlib
  - geopandas

prefix: /Users/gtaddei/Desktop/Progetti/Grano.IT/Risorse/python/grano_experiments
