dataloader:
  batch_size: 128
  num_workers: 0
  persistent_workers: false
  pin_memory: true
early_stopping:
  min_delta: 0.0005
  mode: min
  monitor: val_loss
  patience: 8
model:
  dropout: 0.25
  learning_rate: 0.001
  log_interval: 5
  logging_metrics:
  - rmse
  loss: quantile_loss
  reduce_on_plateau_patience: 5
  weight_decay: 0.0005
trainer:
  accelerator: auto
  devices: auto
  gradient_clip_val: 1.0
  max_epochs: 50
  num_sanity_val_steps: 0
